//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurizmDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fiyatlar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fiyatlar()
        {
            this.Rezervasyon = new HashSet<Rezervasyon>();
        }
    
        public int FiyatId { get; set; }
        public int VarisNoktaId { get; set; }
        public int AracId { get; set; }
        public decimal Fiyat { get; set; }
    
        public virtual Araclar Araclar { get; set; }
        public virtual VarisNoktalari VarisNoktalari { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rezervasyon> Rezervasyon { get; set; }
    }
}
