//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurizmDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VarisNoktalari
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VarisNoktalari()
        {
            this.Fiyatlar = new HashSet<Fiyatlar>();
        }
    
        public int VarisNoktaId { get; set; }
        public string VarisNokta { get; set; }
        public int HavaLimaniId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fiyatlar> Fiyatlar { get; set; }
        public virtual Havalimanlari Havalimanlari { get; set; }
    }
}
